framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: true
    handle_all_throwables: true

    validation:
        enabled: true
        enable_attributes: false

    annotations:
        enabled: false

    session:
        enabled: true
        storage_factory_id: session.storage.factory.native
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
